# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "931d0d3072856b4f056463fdb5b781ed"
name = "mypotatoapp"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
